easy_admin:
  site_name: 'Hybridcore'
  design:
    assets:
      js:
        - '/bundles/cksourceckfinder/ckfinder/ckfinder.js'
        - '/js/setup-ckfinder.js'
    brand_color: 'rgb(44,44,44)'
    form_theme:
      - '@EasyAdmin/form/bootstrap_4.html.twig'
      - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
    menu:
      Hybridcore:
        label: 'Go to website'
        url: "/"
      PostManagement:
        label: 'Blog Management'
        entity: Post
        default: true
      UserManagement:
        label: 'User Management'
        entity: User

        
  entities:
    Post:
      class: 'App\Entity\Post'
      list:
        fields:
          - 'id'
          - 'owner'
          - 'title'
          - 'abstract'
          - 'active'
          - 'createdAt'
          - 'updatedAt'
      form:
        fields:
          - 'owner'
          - { property: 'title', type: 'text', type_options: { attr: { maxlength: 255,required: true }}}
          - { property: 'abstract', type: 'textarea', type_options: { attr: { maxlength: 255,required: true }}}
          - { property: 'content', type: 'fos_ckeditor'}
          - 'active'
    
    User:
      class: 'App\Entity\User'
      disabled_actions: ['new']
      list:
        fields:
          - 'id'
          - 'email'
          - 'fullname'
          - 'roles'
          - 'posts'
          - 'createdAt'
      form:
        actions: ["-delete"]
        fields:
          - { property: 'email', type: 'email', type_options: { attr: { maxlength: 255,required: true }}}
          - { property: 'fullname', type: 'text', type_options: { attr: { maxlength: 255,required: true }}}
          - property: 'roles'
            type: 'choice'
            type_options:
              mapped: true
              expanded: true
              multiple: true
              choices: 
                - ROLE_ADMIN: ROLE_ADMIN

    