easy_admin:
  site_name: 'Slide.ai Dashboard'
  design:
    brand_color: 'rgb(44,44,44)'
    form_theme:
      - '@EasyAdmin/form/bootstrap_4.html.twig'
    menu:
      Slideo:
        label: 'Go to website'
        url: "/"
      UserManagement:
        label: 'User Management'
        entity: User

        
  entities:

    User:
      class: 'App\Entity\User'
      disabled_actions: ['new']
      list:
        fields:
          - 'id'
          - 'email'
          - 'fullname'
          - 'roles'
          - 'createdAt'
          - 'isVerified'
          - 'userType'
          - { property: 'picture', type: 'url'}
      form:
        actions: ["-delete"]
        fields:
          - { property: 'email', type: 'email', type_options: { attr: { maxlength: 255,required: true }}}
          - { property: 'fullname', type: 'text', type_options: { attr: { maxlength: 255,required: true }}}
          - property: 'roles'
            type: 'choice'
            type_options:
              mapped: true
              expanded: true
              multiple: true
              choices: 
                - ROLE_OWNER: ROLE_OWNER
                - ROLE_ADMIN: ROLE_ADMIN
                - ROLE_USER: ROLE_USER
          - 'isVerified'

    