framework:
    default_locale: !php/const \App\Enum\LanguagesEnum::DEFAULT
    translator:
        enabled_locales: !php/const \App\Enum\LanguagesEnum::CONSTANTS
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - !php/const \App\Enum\LanguagesEnum::DEFAULT
