version: '3'

services:
  slideo_symfony:
    container_name: slideo_symfony
    build: ./
    volumes:
      - ./:/var/www/app:delegated
      - /var/www/app/vendor/ # Ignore
      - /var/www/app/node_modules/ # Ignore
      - /var/www/app/var/ # Ignore
    ports:
      - "5500:8000"
    depends_on:
      - slideo_rabbitmq
    env_file:
      - .env.local
    command: ["/bin/bash", "/var/www/app/docker/start.sh"]

  slideo_rabbitmq:
    image: rabbitmq:3-management
    container_name: slideo_rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=slideo 
      - RABBITMQ_DEFAULT_PASS=df711f9a1119082a711a238acf944677
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "5"
    ports:
      - 5502:15672

networks:
  default:
    name: slideo_network
