version: '3'

services:
  slideo_symfony:
    container_name: slideo_symfony
    build: ./
    volumes:
      - ./:/var/www/app:delegated
      - ./docker/php.ini:/usr/local/etc/php/php.ini
      - /var/www/app/vendor/ # Ignore
      - /var/www/app/node_modules/ # Ignore
      - /var/www/app/var/ # Ignore
    ports:
      - "5500:8000"
    env_file:
      - .env.local
    restart: always
    command: ["/bin/bash", "/var/www/app/docker/start.sh"]

networks:
  default:
    name: slideo_network
