version: '3'

services:
  slideo:
    container_name: slideo_symfony
    build: ./
    volumes:
      - ./:/var/www/app:delegated
      - ./docker/php.ini:/usr/local/etc/php/php.ini
      - /var/www/app/vendor/ # Ignore
      - /var/www/app/node_modules/ # Ignore
      - /var/www/app/var/ # Ignore
    ports:
      - "5500:8000"
    command: ["/bin/bash", "/var/www/app/docker/start.sh"]
