version: '3'

services:
  slideo:
    container_name: slideo_symfony
    build: ./
    volumes:
      - ./:/var/www/app
      - ./docker/php.ini:/usr/local/etc/php/php.ini
    ports:
      - "5500:80"
